rage/secret-project-331

- services/headless-lms/src/controllers/auth.rs
Remove: 
use actix_http::Result;
> Fix login page handling

- services/cms/types/imageTypes.d.ts
- services/course-material/types/imageTypes.d.ts
- services/example-exercise/types/imageTypes.d.ts
- services/main-frontend/types/imageTypes.d.ts
- system-tests/types/imageTypes.d.ts
add types to cms/ course-material / example-exericse / main-frontend / system-tests
> Fix image types missing

- services/cms/src/components/editors/EmailEditor.tsx
- services/cms/src/components/editors/PageEditor.tsx
> Handle errors when saving in editor

- kubernetes/base/ingress.yml
- services/cms/src/blocks/supportedGutenbergBlocks.ts
- services/cms/src/styles/Gutenberg/editor-styles.scss
- services/headless-lms/src/controllers/cms/mod.rs
- services/headless-lms/src/controllers/cms/oembed.rs
- services/headless-lms/src/domain/authorization.rs
- services/headless-lms/src/utils/mod.rs
- services/headless-lms/src/utils/url_to_oembed_endpoint.rs
> Implement OEmbed proxy API for supported core/embed variants

- services/cms/src/blocks/Exercise/index.tsx
> Enforce moocfi/exercise can't be InnerBlock

- bin/sqlx-migrate-revert
- bin/sqlx-migrate-run
- bin/sqlx-prepare
- bin/sqlx-prepare-check
> sqlx update

- services/cms/src/pages/pages/[id].tsx
> Refactor CMS useQuery

- services/main-frontend/src/components/page-specific/manage/courses/id/change-request/EditProposalList.tsx
- services/main-frontend/src/components/page-specific/manage/courses/id/change-request/EditProposalPage.tsx
- services/main-frontend/src/components/page-specific/manage/courses/id/feedback/FeedbackList.tsx
- services/main-frontend/src/components/page-specific/manage/courses/id/feedback/FeedbackPage.tsx
- services/main-frontend/src/components/page-specific/manage/courses/id/index/CourseInstancesList.tsx
- services/main-frontend/src/components/page-specific/manage/courses/id/index/CourseLanguageVersionsList.tsx
- services/main-frontend/src/components/page-specific/manage/courses/id/index/ExerciseList.tsx
- services/main-frontend/src/components/page-specific/manage/courses/id/stats/CourseSubmissionsByDay.tsx
- services/main-frontend/src/components/page-specific/manage/courses/id/stats/CourseSubmissionsByWeekdayAndHour.tsx
- services/main-frontend/src/components/page-specific/manage/exercises/id/submissions/ExerciseSubmissionList.tsx
- services/main-frontend/src/components/page-specific/manage/pages/id/history/HistoryList.tsx
- services/main-frontend/src/components/page-specific/manage/pages/id/history/HistoryPage.tsx
- services/main-frontend/src/components/page-specific/manage/pages/id/history/HistoryView.tsx
- services/main-frontend/src/components/page-specific/organizations/index/OrganizationsList.tsx
- services/main-frontend/src/pages/manage/course-instances/[id]/emails.tsx
- services/main-frontend/src/pages/manage/course-instances/[id]/index.tsx
- services/main-frontend/src/pages/manage/course-instances/[id]/points.tsx
- services/main-frontend/src/pages/manage/courses/[id]/pages.tsx
- services/main-frontend/src/pages/manage/exams/[id].tsx
- services/main-frontend/src/pages/manage/exercise-services/index.tsx
- services/main-frontend/src/pages/manage/exercises/[id]/submissions.tsx
- services/main-frontend/src/pages/playground.tsx
- services/main-frontend/src/pages/submissions/[id].tsx
> Refactor useQueries in main-frontend

- services/quizzes/src/components/QuizEditForms/QuizItem/EssayContent/EssayModalContent.tsx
> item.minValue => item.minWords

- services/headless-lms/Cargo.toml
Suggestion taken from sqlx readme.
> Try to speed up development builds by optimizing sqlx macros

- services/course-material/src/components/ContentRenderer/core/embeds/variants/VimeoEmbedBlock.tsx
- services/course-material/src/components/ContentRenderer/core/embeds/variants/YoutubeEmbedBlock.tsx
> Fix figure in vimeo & youtube

- services/course-material/src/components/ContentRenderer/core/embeds/variants/MentimeterEmbedBlock.tsx
- services/course-material/src/components/ContentRenderer/core/embeds/variants/VimeoEmbedBlock.tsx
- services/course-material/src/components/ContentRenderer/core/embeds/variants/YoutubeEmbedBlock.tsx
Student view was rendering <strong> </strong> if bolded
> Fix embed captions to html

- services/main-frontend/src/pages/playground-views.tsx
- shared-module/src/utils/responseHeaders.js
> Accept outside domain iframes and add iframe url (foreign domain) to all specs

- services/headless-lms/server/src/controllers/study_registry/completion_registered_to_study_registry.rs
- services/headless-lms/server/src/controllers/study_registry/completions.rs
- services/headless-lms/server/src/controllers/study_registry/mod.rs
> Improve study registry documentation

- bin/generate-bindings
- services/cms/src/blocks/ExerciseTask/IFrameEditor.tsx
- services/course-material/src/components/ContentRenderer/moocfi/ExerciseBlock/ExerciseTask.tsx
- services/course-material/src/components/ContentRenderer/moocfi/ExerciseBlock/ExerciseTaskIframe.tsx
- services/course-material/src/components/ContentRenderer/moocfi/ExerciseBlock/PeerReviewView/PeerReviewViewImpl.tsx
- services/course-material/src/reducers/exerciseBlockPostThisStateToIFrameReducer.ts
- services/example-exercise/src/components/Editor.tsx
- services/example-exercise/src/components/Exercise.tsx
- services/example-exercise/src/pages/api/grade.ts
- services/example-exercise/src/pages/iframe.tsx
- services/headless-lms/server/generated-docs/CourseMaterialExercise.json
- services/main-frontend/src/components/page-specific/playground-views/PlaygroundExerciseEditorIframe.tsx
- services/main-frontend/src/components/page-specific/playground-views/PlaygroundExerciseIframe.tsx
- services/main-frontend/src/components/page-specific/playground-views/PlaygroundViewSubmissionIframe.tsx
- services/main-frontend/src/components/page-specific/submissions/id/SubmissionIFrame.tsx
- services/main-frontend/src/pages/playground-views.tsx
- services/quizzes/src/hooks/useSendEditorStateOnChange.ts
- services/quizzes/src/hooks/useSendQuizAnswerOnChange.ts
- services/quizzes/src/pages/api/grade.ts
- services/quizzes/src/pages/iframe.tsx
- shared-module/src/components/MessageChannelIFrame.tsx
- shared-module/src/exercise-service-protocol-types-2.ts
- shared-module/src/exercise-service-protocol-types.guard.ts
- shared-module/src/exercise-service-protocol-types.ts
- shared-module/src/locales/en/main-frontend.json
- shared-module/src/styles/respond.ts
- shared-module/src/utils/typeMappter.ts
> Playground view submission view

- services/main-frontend/src/components/FormTextAreaField.tsx
- services/main-frontend/src/components/forms/EditReferenceForm.tsx
- services/main-frontend/src/components/forms/NewReferenceForm.tsx
- services/main-frontend/src/components/page-specific/manage/courses/id/references/index.tsx
- shared-module/src/locales/en/main-frontend.json
- shared-module/src/locales/fi/main-frontend.json
Add error message bellow the text area when the format is not valid or it cannot be parsed.
> Error handling for citations

- services/course-material/src/components/ContentRenderer/util/textParsing.tsx
- shared-module/src/components/Reference.tsx
Update the locations of the citations.
> Citation locations

- services/quizzes/src/components/ParsedText/index.tsx
- services/quizzes/src/components/ParsedText/tagParser.ts
> Latex fix for quizzes

- services/course-material/src/components/ReferencesList.tsx
- shared-module/src/components/Reference.tsx
> Reference fixes

- services/quizzes/src/pages/api/grade.ts
> Quiz grading fix

- kubernetes/dev/access-ingress-internally.yml
- kubernetes/dev/kustomization.yaml
- kubernetes/dev/patch-with-init-container.yml
- kubernetes/dev/patch-without-init-container.yml
- kubernetes/test/access-ingress-internally.yml
- kubernetes/test/kustomization.yaml
- system-tests/src/tests/quizzes/feedback/open.spec.ts
I tried to update everything and curl project-331.local from bin/shell and it didn't work without this PR. Not sure what's going on but at least on my system these changes are still necessary. :thinking:
> Add access-ingress-internally

- services/headless-lms/migrations/20240521125646_store-rejected-submissions.down.sql
- services/headless-lms/migrations/20240521125646_store-rejected-submissions.up.sql
- services/headless-lms/models/.sqlx/query-a84a8c368b478f84639a29031deb0b98ed2e750154d3c802a4728b9e269345a1.json
- services/headless-lms/models/.sqlx/query-cec6fa9b6a186076ff43935930627abd3db4f13c50f37c4998d67bafc26b6c46.json
- services/headless-lms/models/src/exercise_task_submissions.rs
- services/headless-lms/models/src/lib.rs
- services/headless-lms/models/src/library/grading.rs
- services/headless-lms/models/src/library/regrading.rs
- services/headless-lms/models/src/rejected_exercise_slide_submissions.rs
- services/headless-lms/server/src/controllers/course_material/exercises.rs
- services/headless-lms/server/src/controllers/langs.rs
- services/headless-lms/server/src/domain/csv_export/mod.rs
- services/headless-lms/server/src/domain/exercises.rs
When a submission is rejected it is always a bug. With this change the submission that causes the bug is stored so that the problem can be fixed.
> Store rejected submissions for helping to debug why they were rejected.

- LICENSE
- LICENSE-SERVICES-CMS
- README.md
> Make licenses GitHub-detectable
